//Users
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER =  'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';


//Tasks
export const CREATE_TASKS = 'CREATE_TASKS';
export const CREATE_TASKS_SUCCESS = 'CREATE_TASKS_SUCCESS';
export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';